version: "3.9"
services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /app
    ports:
      - "3000:3000"
    image: portfolio
    env_file:
      - .env
